
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE pakan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    berat VARCHAR(255) NOT NULL,
    waktu DATETIME NOT NULL
);
